disable_table_indexes = true
edit_mode = "emacs"
path = ["/home/emallson/.guix-profile/bin", "/home/emallson/.config/guix/current/bin", "/home/emallson/.cabal/bin", "/home/emallson/.emacs.d/bin", "/home/emallson/.config/yarn/global/node_modules/.bin", "/home/emallson/.poetry/bin", "/home/emallson/.cargo/bin", "/home/emallson/.cask/bin", "/home/emallson/.local/bin", "/home/emallson/.nvm/versions/node/v16.8.0/bin", "/usr/local/bin", "/usr/bin", "/bin"]
prompt = "__zoxide_hook;starship prompt"
skip_welcome_message = true
startup = ["alias gst = git status", "alias j = __zoxide_z", "source ~/.config/nu/zoxide.nu", "alias bat = /usr/bin/bat --theme OneHalfLight"]

[color_config]
separator_color = "black"

[env]
BAT_THEME = "Coldark-Cold"
BOOT_JVM_OPTIONS = "-client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none"
BROWSER = "firefox"
CARGO_HOME = "/home/emallson/.cargo/"
CHROME_BIN = "chromium"
CLUTTER_IM_MODULE = "ibus"
EMACSLOADPATH = "/home/emallson/.guix-profile/share/emacs/site-lisp"
GUIX_PROFILE = "/home/emallson/.guix-profile"
HOME = "/home/emallson"
INFOPATH = "/home/emallson/.guix-profile/share/info"
JAVA_HOME = "/usr/lib/jvm/java-8-openjdk-amd64"
LANG = "en_US.UTF-8"
LESS = "-R"
LOGNAME = "emallson"
LSCOLORS = "Gxfxcxdxbxegedabagacad"
LS_COLORS = "tw=30;43:ow=30;43:"
PAGER = "less"

[line_editor]
max_history_size = 100000

[textview]
theme = "Solarized"
