;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        evil-numbers/inc-at-pt
        forward-sexp
        icicle-goto-marker-or-set-mark-command
        icicle-yank-maybe-completing
        indent-for-tab-command
        kill-region
        paredit-backward
        paredit-forward
        sgml-slash
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        icicle-execute-extended-command
        ))
