;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        bibtex-next-field
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        comment-dwim
        evil-backward-char
        evil-backward-word-begin
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-backward-word
        evil-find-char
        evil-forward-char
        evil-forward-word-begin
        evil-insert
        evil-next-line
        evil-numbers/inc-at-pt
        evil-scroll-down
        forward-sexp
        icicle-goto-marker-or-set-mark-command
        icicle-yank-maybe-completing
        indent-for-tab-command
        kill-region
        markdown-exdent-or-delete
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-self-insert-command
        org-table-sum
        paredit-backward
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        sgml-slash
        shm/space
        sp--self-insert-command
        sp-backward-delete-char
        sp-delete-char
        sp-kill-hybrid-sexp
        sp-kill-word
        tern-ac-dot-complete
        tuareg-newline-and-indent
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        describe-key
        evil-ex
        evil-force-normal-state
        evil-normal-state
        helm-mini
        icicle-execute-extended-command
        org-export
        ))
